# Generated by Django 4.0.2 on 2022-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carrito_compra_usuario_producto_pago_compra_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
